cat("Seja bem vinda(o) ao Projeto do Mestrado da Haydée.\n")
cat("Carregando as funções auxiliares.....")
source('R/funcoes_auxiliares.R')
cat(" OK\n")
cat("Carregando funções auxiliares de sumarização....")
source('R/auxiliar_sumarizacao.R')
cat(" OK\n")
cat("Carregando função que gera gráficos de clusters....")
source('R/graficos_de_clusters.R')
cat(" OK\n")
cat("Carregando funções que aplica labels no dataframe da OD....")
source('R/aplica_labels.R')
cat(" OK\n")
carrega_bibliotecas()
cat("\nAlterando o 'working directory' para 'analises'\n")
setwd('analises')
cat("\nAmbiente pronto para ser utilizado, bom trabalho! <3")
